#!/usr/bin/env python3
"""Generates lib/glass-params-table.h from spec/params.json (design.md §11).

    gen-params.py spec/params.json OUTPUT.h
"""
import json
import sys


def c_ident(key):
    return 'GLASS_PARAM_ID_' + key.upper().replace('-', '_')


def c_double(v):
    text = repr(float(v))
    return text if ('.' in text or 'e' in text) else text + '.0'


def main():
    spec_path, out_path = sys.argv[1], sys.argv[2]
    with open(spec_path, encoding='utf-8') as f:
        spec = json.load(f)

    params = spec['params']
    keys = [p['key'] for p in params]
    presets = spec['edge_presets']
    out = []
    w = out.append

    w('/* glass-params-table.h — generated by tools/gen-params.py from spec/params.json.')
    w(' * Do not edit. */')
    w('#pragma once')
    w('')
    w('#include <glib.h>')
    w('')
    w('typedef enum {')
    for p in params:
        w(f'  {c_ident(p["key"])},')
    w('  GLASS_N_PARAMS')
    w('} GlassParamId;')
    w('')
    w('typedef struct {')
    w('  const char *key;')
    w('  const char *uniform;        /* NULL: not a shader uniform */')
    w('  double      default_value;  /* the extension\'s default */')
    w('  double      min, max;')
    w('  gboolean    px;             /* logical px: multiplied by the surface scale */')
    w('  const double *values;       /* NULL, or the allowed values, ending with a negative */')
    w('} GlassParamSpec;')
    w('')
    for p in params:
        if 'values' in p:
            vals = ', '.join(c_double(v) for v in p['values'])
            w(f'static const double glass_param_values_{p["key"].replace("-", "_")}[] = {{ {vals}, -1.0 }};')
    w('')
    w('static const GlassParamSpec glass_param_specs[GLASS_N_PARAMS] = {')
    for p in params:
        uniform = f'"{p["uniform"]}"' if p['uniform'] else 'NULL'
        values = f'glass_param_values_{p["key"].replace("-", "_")}' if 'values' in p else 'NULL'
        w(f'  [{c_ident(p["key"])}] = {{ "{p["key"]}", {uniform}, {c_double(p["default"])}, '
          f'{c_double(p["min"])}, {c_double(p["max"])}, {"TRUE" if p["px"] else "FALSE"}, {values} }},')
    w('};')
    w('')
    w('/* NULL-terminated, for glass_context_list_params(). */')
    w('static const char * const glass_param_keys[GLASS_N_PARAMS + 1] = {')
    for k in keys:
        w(f'  "{k}",')
    w('  NULL')
    w('};')
    w('')
    w('typedef struct {')
    w('  const char *name;')
    w('  gboolean    has[GLASS_N_PARAMS];     /* the keys this material sets */')
    w('  double      values[GLASS_N_PARAMS];')
    w('  float       tint[3];                 /* rgb; the strength is the tint-strength key */')
    w('  gboolean    tint_from_theme;         /* rgb = the theme colour (window, popover) */')
    w('  gboolean    adaptive;                /* FALSE: the foreground follows the theme */')
    w('} GlassMaterialSpec;')
    w('')
    w('/* In GlassMaterial order. */')
    w(f'#define GLASS_N_MATERIALS {len(spec["materials"])}')
    w('static const GlassMaterialSpec glass_material_specs[GLASS_N_MATERIALS] = {')
    for m in spec['materials']:
        values = dict(presets[m['edge']]) if m.get('edge') else {}
        values.update(m['values'])
        for k in values:
            if k not in keys:
                sys.exit(f'material {m["name"]}: unknown key {k}')
        if len(m['tint']) != 3:
            sys.exit(f'material {m["name"]}: tint is rgb (the strength is tint-strength)')
        w('  {')
        w(f'    .name = "{m["name"]}",')
        w('    .has = { ' + ', '.join(f'[{c_ident(k)}] = TRUE' for k in values) + ' },')
        w('    .values = { ' + ', '.join(f'[{c_ident(k)}] = {c_double(v)}' for k, v in values.items()) + ' },')
        w('    .tint = { ' + ', '.join(c_double(v) + 'f' for v in m['tint']) + ' },')
        w(f'    .tint_from_theme = {"TRUE" if m["tint_from_theme"] else "FALSE"},')
        w(f'    .adaptive = {"TRUE" if m["adaptive"] else "FALSE"},')
        w('  },')
    w('};')
    w('')

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(out))


if __name__ == '__main__':
    main()
