#!/usr/bin/env python3
"""Turns spec/adaptive-vectors.json into a C header for tests/test-adaptive.c.

    gen-adaptive-vectors.py spec/adaptive-vectors.json OUTPUT.h
"""
import json
import sys

PREF = {'none': 'GLASS_ADAPTIVE_PREF_NONE', 'light': 'GLASS_ADAPTIVE_PREF_LIGHT', 'dark': 'GLASS_ADAPTIVE_PREF_DARK'}
APPEARANCE = {'light': 'GLASS_ADAPTIVE_LIGHT', 'dark': 'GLASS_ADAPTIVE_DARK', 'unknown': 'GLASS_ADAPTIVE_UNKNOWN'}


def main():
    spec = json.load(open(sys.argv[1], encoding='utf-8'))
    out = ['/* Generated by tools/gen-adaptive-vectors.py from spec/adaptive-vectors.json. */',
           '#pragma once', '',
           'typedef struct { gint64 t_ms; double luma[3]; int expect; } VectorSample;',
           'typedef struct { const char *name; int pref; int n; const VectorSample *samples; } VectorCase;', '']
    for i, case in enumerate(spec['cases']):
        out.append(f'static const VectorSample vector_samples_{i}[] = {{')
        for s in case['samples']:
            l = s['luma']
            out.append(f'  {{ {int(s["t"])}, {{ {l[0]!r}, {l[1]!r}, {l[2]!r} }}, {APPEARANCE[s["expect"]]} }},')
        out.append('};')
    out.append('')
    out.append('static const VectorCase vector_cases[] = {')
    for i, case in enumerate(spec['cases']):
        name = case['name'].replace('"', '\\"')
        out.append(f'  {{ "{name}", {PREF[case["pref"]]}, {len(case["samples"])}, vector_samples_{i} }},')
    out.append('};')
    open(sys.argv[2], 'w', encoding='utf-8').write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
