#!/usr/bin/env python3
"""Generates the public lib/glass-params.h from spec/params.json: one string
constant per key (GLASS_PARAM_BLUR_RADIUS = "blur-radius"), so that a typo in
a key is a compile error in C and an AttributeError in the bindings
(Glass.PARAM_BLUR_RADIUS) rather than a warning at run time.

    gen-params-header.py spec/params.json OUTPUT.h
"""
import json
import sys


def c_ident(key):
    return 'GLASS_PARAM_' + key.upper().replace('-', '_')


def fmt(v):
    return f'{v:g}'


def main():
    spec_path, out_path = sys.argv[1], sys.argv[2]
    with open(spec_path, encoding='utf-8') as f:
        spec = json.load(f)

    out = []
    w = out.append
    w('/* glass-params.h — generated by tools/gen-params-header.py from spec/params.json.')
    w(' * Do not edit.')
    w(' *')
    w(' * SPDX-License-Identifier: MIT')
    w(' */')
    w('#pragma once')
    w('')
    w('#if !defined(GLASS_INSIDE) && !defined(GLASS_COMPILATION)')
    w('#error "Only <glass.h> can be included directly."')
    w('#endif')
    w('')
    for p in spec['params']:
        if 'values' in p:
            rng = 'one of ' + ', '.join(fmt(v) for v in p['values'])
        else:
            rng = f'{fmt(p["min"])} to {fmt(p["max"])}'
        unit = ' logical px' if p['px'] else ''
        w('/**')
        w(f' * {c_ident(p["key"])}:')
        w(' *')
        w(f' * The parameter key `{p["key"]}`: {rng}{unit}, {fmt(p["default"])} by default.')
        w(' * For [method@Glass.Context.set_param] and [method@Glass.Panel.set_param].')
        w(' */')
        w(f'#define {c_ident(p["key"])} "{p["key"]}"')
        w('')

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(out))


if __name__ == '__main__':
    main()
